name: cicd

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v1 #tien ich CLI mo rong conmand, tang hieu nang docker cmd
        id: buildx

      - name: Build Image
        run: docker build -t duy71/cicd:v1 -f Dockerfile .

      - name : Push  Image 
        run: docker push duy71/cicd:v1
